server:
  port: 8080

spring:
  application:
    name: dgca-booking-demo-backend
  datasource:
    url: jdbc:h2:mem:bookingdemo
    driverClassName: org.h2.Driver
    username: sa
    passowrd: ${random.uuid}${random.uuid}
    #password: mXG3kgrxbedh #### onyl for developtment
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false #### enable onyl for developtment
      settings:
        trace: false
        web-allow-others: false

springdoc:
  api-docs:
    path: /api/docs
    enabled: true
  swagger-ui:
    path: /swagger

logging:
  level:
    eu.europa.ec.dgc.booking: DEBUG

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: info,health

#### Example with default values:
#demo:
#  passengers:
#    generator:
#      #### Randomly create passengers or use a list of preconfigured
#      random: false
#      #### Number of additional passengers to be created for the booking reference
#      min: 0
#      max: 2
