apiVersion: v1
kind: Service
metadata:
  name: booking-demo-backend
  namespace: dgca-test
  labels:
    app: booking-demo-backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: booking-demo-backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-demo-backend
  namespace: dgca-test
  labels:
    app: booking-demo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-demo-backend
  template:
    metadata:
      labels:
        app: booking-demo-backend
    spec:
      volumes:
        - name: destination
          secret:
            secretName: destination-service-binding-booking-demo-backend
        - name: xsuaa
          secret:
            secretName: uaa-service-binding-booking-demo-backend
      imagePullSecrets:
        - name: regcred
      containers:
        - name: booking-demo-backend-service
          image: docker.pkg.github.com/courobin/dgca-booking-demo-backend/dgca-booking-demo-backend:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: dgca-booking-backend-demo
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 443
          volumeMounts:
            - name: destination
              mountPath: "/etc/secrets/sapcp/destination/destination-service-instance-booking-demo-backend"
              readOnly: true
            - name: xsuaa
              mountPath: "/etc/secrets/sapcp/xsuaa/uaa-service-instance-booking-demo-backend"
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: 8080

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: uaa-service-instance-booking-demo-backend
  namespace: dgca-test
spec:
  clusterServiceClassExternalName: xsuaa
  clusterServicePlanExternalName: application
  parameters:
    xsappname: xsuaa-kyma-booking-demo-backend
    tenant-mode: dedicated
    oauth2-configuration:
      redirect-uris:
        - https://*/**

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: uaa-service-binding-booking-demo-backend
  namespace: dgca-test
spec:
  instanceRef:
    name: uaa-service-instance-booking-demo-backend

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: destination-service-instance-booking-demo-backend
  namespace: dgca-test
spec:
  clusterServiceClassExternalName: destination
  clusterServicePlanExternalName: lite

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: destination-service-binding-booking-demo-backend
  namespace: dgca-test
spec:
  instanceRef:
    name: destination-service-instance-booking-demo-backend
